### ISSUE TITLE
next_pr_number.py is broken

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-procedures#103]
~30 minutes ago `next_pr_number` said that the next PR number is 8109, while 8109 was already a PR got merged ~3 hours ago. So something is clearly broken, but I don't have the time right now to figure out what it is.

**Comment by bsipocz** [comment]
git blames @Cadair...

**Comment by astrofrog** [comment]
Maybe there is a +1 missing? On phone so can't check...

**Comment by Cadair** [comment]
No I think it's excluding merged PRs. I noticed this the other day.

**Comment by bsipocz** [comment]
#104 has fixed this.
