### ISSUE TITLE
Add README for package maintainers to explain how to update astropy-helpers

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-procedures#105]
Basically telling package maintainers they can add their package to the ``helpers_2`` and ``helpers_3`` files. Also I think we should rename ``update-affiliated`` to ``update-helpers``

**Comment by bsipocz** [comment]
We could also store the package-template based update scripts in `update-affiliated` directory. If that doesn't sounds like a good plan, we can do the rename.

**Comment by astrofrog** [comment]
Right but even then 'affiliated' is not correct since many packages aren't affiliated. What about 'update-packages'

**Comment by bsipocz** [comment]
Yes, I like the idea to change `affiliated`.
