### ISSUE TITLE
PR_CONSISTENCY: broken script, missed out backports

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-procedures#69]
Running the changelog scripts on a different machine, I got a set of PRs for backport that are milestoned for 2.0.3. These were however not suggested at the time of doing the release, or in fact before that or even during doing the 3.0RC1 release.

I need to investigate what goes wrong, and opening this PR as a reminder. These are the ones that were not backported for 2.0.3. All of them are without a changelog entry, so the easy workaround is to remilestone them to 2.0.4. Needless to say we need to find the bug in the scripts.

```
# Pull request #6340: Using more stringent locale for docs build testing
git cherry-pick -m 1 5365124ecd17e29015fa016bcd6ad96bcb344a41
# Pull request #6738: Ignore lastfailed (direct pytest invokation) file
git cherry-pick -m 1 8c1e3f905a34f8e5ef91036414d194663f0dd836
# Pull request #6736: Explain d3d in examples and docstring
git cherry-pick -m 1 ffe37af979504da1324b06e0ccbc6fd8b63e2bee
# Pull request #6745: Update broken and permanently redirected links
git cherry-pick -m 1 135589ff117042de5ef604889e851ecea760b759
```

**Comment by astrofrog** [comment]
Oops :-/ Is this a Python 2 vs 3 issue?? Are the json files with the PR details different on the two machines?

**Comment by bsipocz** [comment]
No, I use python3 everywhere. But had some issues with the python install on the other (borrowed) machine anyway, so maybe I can't avoid looking into them.

**Comment by astrofrog** [comment]
Can you check whether the JSON files are the same on both machines?

**Comment by bsipocz** [comment]
Well, sadly the original jsons were overwritten. Running them now at the same time, the disturbing discovery is that both versions include entries that are missing from the other.

**Comment by astrofrog** [comment]
@bsipocz - sounds good, so shall we close this now #72 is merged?

**Comment by bsipocz** [comment]
Yes, while I'm not 100% certain that my theory above was right, let's assume it is and close this. We can always reopen if this turns out to be an issue again.
