### ISSUE TITLE
Switch away from pygithub

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-procedures#77]
Because license.

**Comment by Mariatta** [comment]
I recommend checking out [gidgethub](https://gidgethub.readthedocs.io/en/latest/). If you'd like I can look into converting one of the scripts into gidgethub? Assuming we can use Python 3.6+ here?

**Comment by bsipocz** [comment]
Sure, please go ahead. I very much used to the ways of pygithub, but if we switch I don't have preferences either way.

Also, we might have already assumed python 3.7 in some of the scripts?

**Comment by pllim** [comment]
I attempted to convert stuff to `github3` in #79 but the PR is stale by now, so I, too, welcome a fresh approach.
